name: Build Workflow

## trigger on push on main branch after pull request
# also run on pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup golang 1.12.6
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          check-latest: true

#      - name: Run go test
#        run: go test -v ./...

      - name: Run go build
        run: go build -v ./...

      - name: Run tests with gotestsum
        run: gotestsum --junitfile test-report.xml -- -v ./...